# Generated by Django 4.2.6 on 2023-11-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Enter', max_length=200)),
                ('question_title', models.CharField(default='Default', max_length=200)),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'Text Field'), ('DF', 'Date Field'), ('RB', 'Radio Button'), ('EM', 'Email')], default='MR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_textfield', models.TextField(default='Enter Text Here', max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
                ('question', models.ForeignKey(default='Enter', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'choice'), ('question', 'position')},
            },
        ),
    ]
