# Generated by Django 4.2.6 on 2023-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.TextField(verbose_name='Choice'),
        ),
    ]
